// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9nm-dbIf8DXt9OtplN3AOvFGSrgFq3UI',
    appId: '1:1060105225005:web:556163c040a6745b2809a4',
    messagingSenderId: '1060105225005',
    projectId: 'box-pusher-2fddc',
    authDomain: 'box-pusher-2fddc.firebaseapp.com',
    storageBucket: 'box-pusher-2fddc.firebasestorage.app',
    measurementId: 'G-5PCCYW3EDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_XtB5NM9r4x8Njh9dVJl1tj7uC7PrWLM',
    appId: '1:1060105225005:android:41f11be2593cb4582809a4',
    messagingSenderId: '1060105225005',
    projectId: 'box-pusher-2fddc',
    storageBucket: 'box-pusher-2fddc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCne7JJwWYLHQIdF9l_tAdoSnRKHLSJrSM',
    appId: '1:1060105225005:ios:b1019093343e18682809a4',
    messagingSenderId: '1060105225005',
    projectId: 'box-pusher-2fddc',
    storageBucket: 'box-pusher-2fddc.firebasestorage.app',
    iosBundleId: 'com.example.boxPusher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCne7JJwWYLHQIdF9l_tAdoSnRKHLSJrSM',
    appId: '1:1060105225005:ios:b1019093343e18682809a4',
    messagingSenderId: '1060105225005',
    projectId: 'box-pusher-2fddc',
    storageBucket: 'box-pusher-2fddc.firebasestorage.app',
    iosBundleId: 'com.example.boxPusher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9nm-dbIf8DXt9OtplN3AOvFGSrgFq3UI',
    appId: '1:1060105225005:web:175285868b9bccef2809a4',
    messagingSenderId: '1060105225005',
    projectId: 'box-pusher-2fddc',
    authDomain: 'box-pusher-2fddc.firebaseapp.com',
    storageBucket: 'box-pusher-2fddc.firebasestorage.app',
    measurementId: 'G-EHFZVM3YZQ',
  );

}