name: Create Git Tag

on:
  push:
    branches:
      - main

jobs:
  create-git-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Check app version"
        run: |
          echo "v$(yq '.version' pubspec.yaml)"
