name: Gh-Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.5"
      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /box_pusher/v0_2_0/
          webRenderer: canvaskit
